name: Build Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Create Release Zip
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        mkdir -p artifacts
        zip -j artifacts/movieoftheweek.zip bin/Debug/net6.0/MovieOfTheWeek.dll manifest.json
        
    - name: Upload Artifacts
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v2
      with:
        name: plugin
        path: artifacts/movieoftheweek.zip 